sponsor_all:
    path:  /sponsor
    defaults: { _controller: GeneralBundle:Sponsor:allSponsor, _format: ~ }
    requirements:
        _method: GET

sponsor_get:
    path:  /sponsor/{id}
    defaults: { _controller: GeneralBundle:Sponsor:getSponsor, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

sponsor_post:
    path:  /sponsor
    defaults: { _controller: GeneralBundle:Sponsor:postSponsor, _format: ~ }
    requirements:
        _method: POST

sponsor_put:
    path:  /sponsor/{id}
    defaults: { _controller: GeneralBundle:Sponsor:putSponsor, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

sponsor_delete:
    path:  /sponsor/{id}
    defaults: { _controller: GeneralBundle:Sponsor:deleteSponsor, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"