tournament_all:
    path:  /tournament
    defaults: { _controller: GeneralBundle:Tournament:allTournament, _format: ~ }
    requirements:
        _method: GET

tournament_get:
    path:  /tournament/{id}
    defaults: { _controller: GeneralBundle:Tournament:getTournament, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

tournament_get_byAdmin:
    path:  /tournament/admin/{userId}
    defaults: { _controller: GeneralBundle:Tournament:getTournamentsByAdmin, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

tournament_post:
    path:  /tournament
    defaults: { _controller: GeneralBundle:Tournament:postTournament, _format: ~ }
    requirements:
        _method: POST

tournament_put:
    path:  /tournament/{id}
    defaults: { _controller: GeneralBundle:Tournament:putTournament, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

tournament_delete:
    path:  /tournament/{id}
    defaults: { _controller: GeneralBundle:Tournament:deleteTournament, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"

tournament_start:
    path:  /tournament/startTournament/{id}
    defaults: { _controller: GeneralBundle:Tournament:startTournament, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

tournament_close_inscription:
    path:  /tournament/closeInscription/{id}
    defaults: { _controller: GeneralBundle:Tournament:closeInscriptionTournament, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

tournament_close_group:
    path:  /tournament/closeGroups/{id}
    defaults: { _controller: GeneralBundle:Tournament:closeGroupsTournament, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

tournament_create_draw:
    path:  /tournament/createDraw/{id}
    defaults: { _controller: GeneralBundle:Tournament:createDrawTournament, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"