user_all:
    path:  /user
    defaults: { _controller: GeneralBundle:User:allUser, _format: ~ }
    requirements:
        _method: GET

user_get:
    path:  /user/{id}
    defaults: { _controller: GeneralBundle:User:getUser, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

user_post:
    path:  /user
    defaults: { _controller: GeneralBundle:User:postUser, _format: ~ }
    requirements:
        _method: POST

user_put:
    path:  /user/{id}
    defaults: { _controller: GeneralBundle:User:putUser, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

user_delete:
    path:  /user/{id}
    defaults: { _controller: GeneralBundle:User:deleteUser, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"

user_login:
    path:  /user/login/{email}/{password}
    defaults: { _controller: GeneralBundle:User:loginUser, _format: ~ }
    requirements:
        _method: GET