web:
    type: rest
    resource: routing_web.yml
    name_prefix: web_
    
user:
    type: rest
    resource: routing_user.yml
    name_prefix:  user_

userPreference:
    type: rest
    resource: routing_userPreference.yml
    name_prefix:  userPreference_

tournament:
    type: rest
    resource: routing_tournament.yml
    name_prefix:  tournament_

status:
    type: rest
    resource: routing_status.yml
    name_prefix:  status_

userRole:
    type: rest
    resource: routing_userRole.yml
    name_prefix:  userRole_

sponsor:
    type: rest
    resource: routing_sponsor.yml
    name_prefix:  sponsor_

recordal:
    type: rest
    resource: routing_recordal.yml
    name_prefix:  recordal_

notification:
    type: rest
    resource: routing_notification.yml
    name_prefix:  notification_

annotation:
    type: rest
    resource: routing_annotation.yml
    name_prefix:  annotation_

category:
    type: rest
    resource: routing_category.yml
    name_prefix:  category_

pair:
    type: rest
    resource: routing_pair.yml
    name_prefix:  pair_

inscription:
    type: rest
    resource: routing_inscription.yml
    name_prefix:  inscription_

observation:
    type: rest
    resource: routing_observation.yml
    name_prefix:  observation_

groupCategory:
    type: rest
    resource: routing_groupcategory.yml
    name_prefix:  group_

game:
    type: rest
    resource: routing_game.yml
    name_prefix:  game_

schedule:
    type: rest
    resource: routing_schedule.yml
    name_prefix:  schedule_

util:
    type: rest
    resource: routing_util.yml
    name_prefix:  util_

info:
    type: rest
    resource: routing_info.yml
    name_prefix:  info_