define({
	"sections":[
            {'key':'basicInfo', 'text':'Basic Information'},
            {'key':'annotations', 'text':'Annotations'},
            {'key':'tournaments', 'text':'Tournaments'},
            {'key':'inscriptions', 'text':'Inscriptions'},
            {'key':'games', 'text':'Games'},
            {'key':'pairs', 'text':'My pairs Info'},
    ],
	"fields":{
		"email":"Email",
		"name":"Name",
		"lastName":"LastName",
		"registrationDate":"Registration Date",
		"status":"Status",
		"address":"Address",
		"city":"City",
		"country":"Country",
		"cp":"Postal Code",
		"firstPhone":"First Phone",
		"gameLevel":"Game Level",
		"secondPhone":"Second Phone",
		"gender":"Gender"
	},
	"buttonBasicInfo":"Edit Profile",
	"cancelButtonTitle":"Cancel",
	"saveButtonTitle":"Save",
	"loadingMessage":"Loading",
	"modalTitleProfile":"Edit Profile",
	"modalTitleInscription":"Do Inscription To",
	"modalTitleObservation": "Edit Observations",
	"modalTitleAnnotation": "Insert Annotation",
	"confirmSaveProfile":"Are you sure save changes?",
	"confirmDeleteAnnotation": "Are you sure delete annotation",
	"tournamentsFields":{
		"name":"Name",
		"admin":"Admin",
		"startInscriptionDate":"Start Inscription Date",
		"startGroupDate":"Start Tournament",
		"status":"Status",
		"options":"Options"
	},
	"inscriptionsFields":{
		"pair":"Pair",
		"category":"Category",
		"group":"Group",
		"status":"Status",
		"options":"Options"
	},
	"pairsFields":{
		"pair":"Pair"
	},
	"annotationsFields":{
		"creationDate":"Creation Date",
		"text":"Text",
		"status":"Status",
		"options":"Options"
	},
	"gamesFields":{
		"gameDate":"Match Date",
		"tournament":"Tournament",
		"status":"Status",
		"options":"Options"
	},
	"doInscription":"Sign Up",
	"viewObservation":"View Observations",
	"modifyAnnotation": "Modify Annotation",
	"deleteAnnotation": "Delete Annotation",
	"createAnnotation": "New Annotation",
	"insertAnnotation": "Insert text",
	"deleteInscription": "Delete Observation",
	"AreSureDeleteInscription": "Are you sure to delete Inscription?",
	"pair":"Pair",
	"category":"Category",
	"placeholderPair":"Insert your pair name",
	"placeholderCategory":"-- Select your category --",
	"observations":"Observations",
	"addObservation":"Add Observation",
	"date":"Date",
	"fromHour":"From Hour",
	"toHour":"To Hour",
	"available":"Available",
	"noObservations":"Don´t have observations in this inscription",
	"someObservationsAreInvalid":"Some observations are invalid, there was not saved",
	"successMessageTextInscription":"Your inscription send succesfully",
	"successMessageDeleteInscription":"Your inscription has deleted succesfully",
	"successMessageTextObservations":"Your observations saved succesfully",
	"errorMessageDeleteInscription":"Your inscription has not been deleted"
});